/* Auto-generated by genmsg_cpp for file /home/sophie/ROS/src/walle/msg/gestures.msg */
#ifndef WALLE_MESSAGE_GESTURES_H
#define WALLE_MESSAGE_GESTURES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace walle
{
template <class ContainerAllocator>
struct gestures_ {
  typedef gestures_<ContainerAllocator> Type;

  gestures_()
  : header()
  , wave(false)
  {
  }

  gestures_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , wave(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _wave_type;
  uint8_t wave;


  typedef boost::shared_ptr< ::walle::gestures_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::walle::gestures_<ContainerAllocator>  const> ConstPtr;
}; // struct gestures
typedef  ::walle::gestures_<std::allocator<void> > gestures;

typedef boost::shared_ptr< ::walle::gestures> gesturesPtr;
typedef boost::shared_ptr< ::walle::gestures const> gesturesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::walle::gestures_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::walle::gestures_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace walle

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::walle::gestures_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::walle::gestures_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::walle::gestures_<ContainerAllocator> > {
  static const char* value() 
  {
    return "550b3e68ec2eb11e4ec54790dcf97aff";
  }

  static const char* value(const  ::walle::gestures_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x550b3e68ec2eb11eULL;
  static const uint64_t static_value2 = 0x4ec54790dcf97affULL;
};

template<class ContainerAllocator>
struct DataType< ::walle::gestures_<ContainerAllocator> > {
  static const char* value() 
  {
    return "walle/gestures";
  }

  static const char* value(const  ::walle::gestures_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::walle::gestures_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
bool wave\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::walle::gestures_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::walle::gestures_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::walle::gestures_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::walle::gestures_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.wave);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct gestures_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::walle::gestures_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::walle::gestures_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "wave: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wave);
  }
};


} // namespace message_operations
} // namespace ros

#endif // WALLE_MESSAGE_GESTURES_H

