/* Auto-generated by genmsg_cpp for file /home/sophie/ROS/src/walle/msg/HRI.msg */
#ifndef WALLE_MESSAGE_HRI_H
#define WALLE_MESSAGE_HRI_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace walle
{
template <class ContainerAllocator>
struct HRI_ {
  typedef HRI_<ContainerAllocator> Type;

  HRI_()
  {
  }

  HRI_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::walle::HRI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::walle::HRI_<ContainerAllocator>  const> ConstPtr;
}; // struct HRI
typedef  ::walle::HRI_<std::allocator<void> > HRI;

typedef boost::shared_ptr< ::walle::HRI> HRIPtr;
typedef boost::shared_ptr< ::walle::HRI const> HRIConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::walle::HRI_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::walle::HRI_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace walle

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::walle::HRI_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::walle::HRI_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::walle::HRI_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::walle::HRI_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::walle::HRI_<ContainerAllocator> > {
  static const char* value() 
  {
    return "walle/HRI";
  }

  static const char* value(const  ::walle::HRI_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::walle::HRI_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#basically a list of gestures as noted in config file\n\
";
  }

  static const char* value(const  ::walle::HRI_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::walle::HRI_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::walle::HRI_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HRI_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::walle::HRI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::walle::HRI_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // WALLE_MESSAGE_HRI_H

