/* Auto-generated by genmsg_cpp for file /home/sophie/ROS/src/walle/msg/pointerpos.msg */
#ifndef WALLE_MESSAGE_POINTERPOS_H
#define WALLE_MESSAGE_POINTERPOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace walle
{
template <class ContainerAllocator>
struct pointerpos_ {
  typedef pointerpos_<ContainerAllocator> Type;

  pointerpos_()
  : Header()
  , positionx(0)
  , positionz(0)
  , servo(0)
  {
  }

  pointerpos_(const ContainerAllocator& _alloc)
  : Header(_alloc)
  , positionx(0)
  , positionz(0)
  , servo(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
   ::std_msgs::Header_<ContainerAllocator>  Header;

  typedef int32_t _positionx_type;
  int32_t positionx;

  typedef int32_t _positionz_type;
  int32_t positionz;

  typedef int32_t _servo_type;
  int32_t servo;


  typedef boost::shared_ptr< ::walle::pointerpos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::walle::pointerpos_<ContainerAllocator>  const> ConstPtr;
}; // struct pointerpos
typedef  ::walle::pointerpos_<std::allocator<void> > pointerpos;

typedef boost::shared_ptr< ::walle::pointerpos> pointerposPtr;
typedef boost::shared_ptr< ::walle::pointerpos const> pointerposConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::walle::pointerpos_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::walle::pointerpos_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace walle

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::walle::pointerpos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::walle::pointerpos_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::walle::pointerpos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2d5351b051f027c38ab4cedd68d85d7c";
  }

  static const char* value(const  ::walle::pointerpos_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2d5351b051f027c3ULL;
  static const uint64_t static_value2 = 0x8ab4cedd68d85d7cULL;
};

template<class ContainerAllocator>
struct DataType< ::walle::pointerpos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "walle/pointerpos";
  }

  static const char* value(const  ::walle::pointerpos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::walle::pointerpos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header Header\n\
\n\
int32 positionx\n\
int32 positionz\n\
int32 servo\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::walle::pointerpos_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::walle::pointerpos_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.Header);
    stream.next(m.positionx);
    stream.next(m.positionz);
    stream.next(m.servo);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct pointerpos_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::walle::pointerpos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::walle::pointerpos_<ContainerAllocator> & v) 
  {
    s << indent << "Header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "positionx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.positionx);
    s << indent << "positionz: ";
    Printer<int32_t>::stream(s, indent + "  ", v.positionz);
    s << indent << "servo: ";
    Printer<int32_t>::stream(s, indent + "  ", v.servo);
  }
};


} // namespace message_operations
} // namespace ros

#endif // WALLE_MESSAGE_POINTERPOS_H

